spring:
  application:
    name: spring-boot-kafka

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

rabbitmq:
  queue:
    test: test_queue

logging:
  level:
    root: info
    com.sts: debug
    org.springframework.web: debug
    org.springframework.amqp: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%file:%line] - %msg%n"